import json
import os
import argparse

import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import utils.pitfall_cameras_utils as pc
import utils.utils as utils

def merge_coco_json(coco_list):
    """ 
    Merges the COCO JSON files in the provided list to a single JSON object.
    
    :param coco_list: List of file paths to the COCO-JSON files we want to merge.
    """

    with open(coco_list[0], "r") as f:
        coco0 = json.load(f)
    merged_info = coco0["info"]
    merged_license = coco0["license"]
    merged_categories = coco0["categories"]

    merged_images = []
    merged_annotations = []
    seen_images = set()
    seen_annotations = set()
    total_files = len(coco_list)

    image_id_offset = 0
    annotation_id_offset = 0
    for index, file in enumerate(coco_list):
        # Load datasets
        with open(file, "r") as f:
            coco = json.load(f)

        image_id_offset = 0        
        for img in coco["images"]:
            img_id = img["id"]
            if img_id in seen_images: 
                raise ValueError(f"Image {img_id} already seen!")
            
            merged_images.append(img)
            seen_annotations.add(img_id)
        
        for ann in coco["annotations"]:
            ann_id = ann["id"]
            if ann_id in seen_annotations: raise ValueError(f"Annotation {ann_id} already seen!")
            merged_annotations.append(ann)
            seen_annotations.add(ann_id)

        image_id_offset += len(coco["images"])
        annotation_id_offset += len(coco["annotations"])

        # Print progress
        print(f"--- Processed {index} out of {total_files} files.")
   
    print(f"Sum of images: {image_id_offset}\nMerged images: {len(merged_images)}")
    print(f"Sum of anns: {annotation_id_offset}\nMerged anns: {len(merged_annotations)}")

    merged = {}
    merged["info"] = merged_info
    merged["license"] = merged_license
    merged["images"] = merged_images
    merged["annotations"] = merged_annotations
    merged["categories"] = merged_categories

    return merged


def merge_all_in_dir(src_dir, dest_path):
    files_to_merge = [os.path.join(src_dir, f) for f in os.listdir(src_dir) if os.path.isfile(os.path.join(src_dir, f)) and f.endswith(".json")]
    merged = merge_coco_json(coco_list=files_to_merge)
    merged["info"] = "Annotations for object detections in the images collection in the ECOSTACK-project's controlled conditions experiment, where different insect species are photographed in a tray with paper and soil backgrounds - this set uses only the paper instances. The images were taken in May-August 2023. These COCO-annotations are generated by Stinna Danger and Mikkel Berg for their thesis project at Aarhus University at the Department of Computer Science with biodiversity group at the Department of Ecoscience. The bounding boxes were found using Asger Svennings flatbug-model."
    utils.save_json(merged=merged, destination_path=dest_path)
    
def main():
    # Set up command-line argument parsing
    parser = argparse.ArgumentParser(description="Merge the json files for COCO-datasets in a directory.")
    src_dir = "annotations/controlled-conditions/original-files/flatbug-coco/"
    dest_path = "annotations/controlled-conditions/controlled-conditions_all.json"
    
    merge_all_in_dir(src_dir=src_dir, dest_path=dest_path)

if __name__ == "__main__":
    main()